ALTER TABLE ventas
  ADD COLUMN IF NOT EXISTS adelanto NUMERIC(12,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS agencia TEXT,
  ADD COLUMN IF NOT EXISTS numero_guia TEXT,
  ADD COLUMN IF NOT EXISTS estado_envio TEXT,
  ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW();

CREATE INDEX IF NOT EXISTS idx_ventas_cliente_created
  ON ventas(cliente_id, created_at DESC);
